### ISSUE TITLE
Add new `evidence.defaultPort` configuration setting

### ISSUE THREAD

**Issue by RandomFractals** [evidence-dev/evidence-vscode#52]
In addition to the dynamic free port discovery in #31.

- [x] Set it to the port number `3000` used by the Evidence as default in all docs and examples.
- [x] Read new default port setting in `config.ts`
- [x] Use new `evidence.defaultPort` config setting instead of current constant in `preview.ts` for page previews and server runs

**Comment by RandomFractals** [comment]
This now works to reset default Evidence dev server.

@archiewood to test this new configuration setting:

- Start dev server
- Verity that it starts on the default port `3000`
- Stop dev server
- Go to File -> Preferences -> Settings -> Extensions -> Evidence settings you see in the screenshot above
- Change Default Port setting to `5000`
- Start dev server
- Note how server is started with port `5000` param
- View ext. logging related to used port, terminal process id, and requested preview pages via #51.

**Note**: you need to stop and restart the server for the new setting to take effect.

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/1d24341b-4632-4376-9ba1-ab595a4f0b17)

**Comment by archiewood** [comment]
@RandomFractals All worked fine untill I tried to open port 5000. 

At which point it opened 5001

See gif
![CleanShot 2023-06-01 at 12 02 24](https://github.com/evidence-dev/evidence-vscode/assets/58074498/cb5cae25-9927-4d02-b55a-3b05e30ff21a)

It turns out I had another process running on `5000`, but it didn't change the port that the simple browser opened to match


When I tried with `6000` this worked fine

![CleanShot 2023-06-01 at 12 06 15](https://github.com/evidence-dev/evidence-vscode/assets/58074498/26f54077-ac8e-4c69-b458-c8162bde7828)

**Comment by archiewood** [comment]
If we wanted to avoid this we could maybe pass vite strictPort flag which will fail if the port is busy:
https://vitejs.dev/config/server-options.html#server-strictport

**Comment by RandomFractals** [comment]
oh, so #31 works. I just need to patch open preview url? Great test and recording. Thank you.

**Comment by RandomFractals** [comment]
Will have to enable this feature for github codespaces too. will allow port reassignment in codespaces.

Current disconnect is in the command we issue when using remote node instance:

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/1c60e16b-551f-4e69-af00-5b4eb0681d26)

**Comment by RandomFractals** [comment]
Resolved:

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/9e02a8e3-5631-41d6-bea0-67f720a07c78)
